# Generated by Django 5.0 on 2024-02-23 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_techername_delete_meta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='techername',
            new_name='teachername',
        ),
    ]
