# Generated by Django 5.0 on 2024-02-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='emai',
            new_name='email',
        ),
    ]
